//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.15 at 09:32:00 PM MESZ 
//

/**
 *   This file is part of ancat.
 *
 *   ancat is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   ancat is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with ancat.  If not, see <http://www.gnu.org/licenses/>.
 */

package ancat.importer.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dimension_width" type="{http://www.w3.org/2001/XMLSchema}short" default="600" />
 *       &lt;attribute name="dimension_height" type="{http://www.w3.org/2001/XMLSchema}short" default="600" />
 *       &lt;attribute name="useoutput" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="implementation" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="graphtool.visualizers.DirectedModelVisualizer"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "inspector")
public class Inspector {

    @XmlAttribute(name = "dimension_width")
    protected Short dimensionWidth;
    @XmlAttribute(name = "dimension_height")
    protected Short dimensionHeight;
    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object useoutput;
    @XmlAttribute(required = true)
    protected String implementation;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the dimensionWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getDimensionWidth() {
        if (dimensionWidth == null) {
            return ((short) 600);
        } else {
            return dimensionWidth;
        }
    }

    /**
     * Sets the value of the dimensionWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDimensionWidth(Short value) {
        this.dimensionWidth = value;
    }

    /**
     * Gets the value of the dimensionHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getDimensionHeight() {
        if (dimensionHeight == null) {
            return ((short) 600);
        } else {
            return dimensionHeight;
        }
    }

    /**
     * Sets the value of the dimensionHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDimensionHeight(Short value) {
        this.dimensionHeight = value;
    }

    /**
     * Gets the value of the useoutput property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUseoutput() {
        return useoutput;
    }

    /**
     * Sets the value of the useoutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUseoutput(Object value) {
        this.useoutput = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
